version: '3.7'

services:
  fastapi:
    container_name: main-fastapi
    build: ./FastAPI
    volumes:
      - ./FastAPI:/app
    ports:
      - 5000:5000
    tty: true
    networks:
      - another_api

  main-react:
    container_name: main-react
    image: node:14.13.1
    volumes:
      - ./front/main-react:/home/app/frontend
    ports:
      - 3000:3000
    working_dir: /home/app/frontend
    command: sh -c "npm start"

networks:
  another_api:
    external: true
